version: "3.8"
services:

  backend:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    depends_on:
      - postgres
#    env_file:
#      - .env

  postgres:
    image: 'postgres:14.3'
    volumes:
      - pgdata:/var/lib/postgresql/data
#    env_file:
#      - .env
    ports:
      - "5432:5432"


volumes:
  pgdata: