# Generated by Django 4.2.5 on 2023-09-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book_supporting_resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "author",
                    models.ManyToManyField(to="book_supporting_resources.author"),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_supporting_resources.condition",
                    ),
                ),
                ("genre", models.ManyToManyField(to="book_supporting_resources.genre")),
            ],
        ),
    ]
